name: godot-ci
on:
  push:
    branches: [ main ]

jobs:
  export-game:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.6.1
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export game
        run: |
          mkdir -p build
          godot --headless --export-release "2dgame-windows" build/game.exe

      - name: Upload to Release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: build/game.exe
          allowUpdates: true
